include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for OpenClash Guard
LUCI_DEPENDS:=+luci-base +rpcd +uclient-fetch
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=mythic3011

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
