from __future__ import annotations

from ..compiler import compile_adguard_home_plan
from ..models import AdGuardHomePlan
from ..settings import BASE_URL, REPO_URL


def render_adguard_home(plan: AdGuardHomePlan | None = None) -> str:
    """Render the local AI domain delta as an AdGuard Home DNS blocklist."""
    plan = plan or compile_adguard_home_plan()
    public_url = f"{BASE_URL}/rule/{plan.output_file}"
    lines = [
        "! Generated by internal/python/generate_ai_profiles.py",
        f"! REPO: {REPO_URL}",
        f"! FILTER-URL: {public_url}",
        "!",
        "! AdGuard Home DNS blocklist. This file BLOCKS DNS names; it does not proxy or route traffic.",
        "! Projection scope: local DOMAIN / DOMAIN-SUFFIX deltas plus the checked-in upstream DLC snapshot.",
        "! Refresh upstream coverage explicitly with: python internal/python/generate_ai_profiles.py --refresh-upstream-hosts",
        "! DOMAIN is rendered as an exact domains-only rule.",
        "! DOMAIN-SUFFIX / DLC suffix entries are rendered as Adblock-style ||domain^ to include subdomains.",
    ]
    if plan.snapshot_refreshed_at:
        lines.append(f"! UPSTREAM-REFRESHED-AT: {plan.snapshot_refreshed_at}")
    else:
        lines.append("! WARNING: upstream snapshot is missing; this output contains local deltas only.")

    current_service = None
    for rule in plan.rules:
        if rule.service_id != current_service:
            lines.extend(["", f"! {rule.service_group} ({rule.service_id})"])
            current_service = rule.service_id
        if rule.kind == "exact":
            lines.append(rule.domain)
        elif rule.kind == "suffix":
            lines.append(f"||{rule.domain}^")
        else:
            lines.append(f"/{rule.domain}/")

    return "\n".join(lines).rstrip()
