from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import subprocess

from ..common import yaml_string
from ..settings import REPO_URL


_REPOSITORY_ROOT = Path(__file__).resolve().parents[4]


def _generated_at() -> str:
    return datetime.now(timezone.utc).isoformat()


def _repository_version() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=_REPOSITORY_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError, UnicodeError):
        return "unknown"
    return result.stdout.strip() or "unknown"


def render_rule_file(
    provider_key: str,
    group: str,
    payload: list[str],
    extra_comments: list[str] | None = None,
) -> str:
    lines = [
        "# Generated by internal/python/generate_ai_profiles.py",
        f"# REPO: {REPO_URL}",
        f"# SOURCE: {REPO_URL}/blob/main/internal/python/generate_ai_profiles.py",
        f"# RULE-PROVIDER: {provider_key}",
        f"# GROUP: {group}",
        f"# TOTAL: {len(payload)}",
        f"# GENERATED-AT: {_generated_at()}",
        f"# VERSION: {_repository_version()}",
    ]
    if extra_comments:
        lines.append("")
        lines.extend(extra_comments)
    lines.extend(["", "payload:"])
    lines.extend(f"  - {yaml_string(rule)}" for rule in payload)
    return "\n".join(lines)

def render_process_rule_file(
    provider_key: str,
    group: str,
    payload: list[str],
    warning_lines: list[str] | None = None,
) -> str:
    if warning_lines is None:
        from ..catalog import load_catalog

        warning_lines = list(load_catalog().process_rules_warning)
    return render_rule_file(
        provider_key=provider_key,
        group=group,
        payload=[f"PROCESS-NAME,{name}" for name in payload],
        extra_comments=warning_lines,
    )

def render_comment_rule_file(body_lines: list[str]) -> str:
    return "\n".join(
        [
            "# Generated by internal/python/generate_ai_profiles.py",
            f"# REPO: {REPO_URL}",
            f"# SOURCE: {REPO_URL}/blob/main/internal/python/generate_ai_profiles.py",
            *body_lines,
        ]
    )

