# Custom_OpenClash_Rules
# {{TITLE}}
# 適用於需要 AI 分流與 DNS 洩漏保護的 OpenWrt / OpenClash 場景
# 基於 Custom_Clash.yaml 精簡：僅保留 AI 分流與基礎網路配置
{{PROFILE_POLICY_NOTES}}
# GENERATED by internal/python/generate_ai_profiles.py. Do not edit manually.

# ==================== 端口配置 Port Configuration ====================
port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
allow-lan: true
bind-address: "*"
mode: rule
tcp-concurrent: true
unified-delay: true

# ==================== 代理提供者 Proxy Provider ====================
proxy-providers:
  provider1:
    type: http
    url: "url"
    interval: 3600
    path: ./proxy_provider/provider1.yaml
    proxy: DIRECT
    header:
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204
    override:
      skip-cert-verify: true
      udp: true
    exclude-filter: {{PROVIDER_NOISE_EXCLUDE_PATTERN}}

# ==================== 地理数据库配置 GeoData Configuration ====================
geox-url:
  mmdb: https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb
  geoip: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true

# ==================== 日志与控制 ====================
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
{{SECRET_LINES}}

# ==================== 配置文件存储 Profile ====================
profile:
  store-selected: true
  store-fake-ip: true

# ==================== TUN 虚拟网卡配置 ====================
tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
  auto-detect-interface: false
  auto-route: false
  auto-redirect: false
  strict-route: false
  endpoint-independent-nat: true

# ==================== DNS 配置 ====================
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  fake-ip-filter-mode: blacklist
  respect-rules: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
    - https://dns.adguard-dns.com/dns-query
  direct-nameserver:
    - https://127.0.0.1:5053/dns-query
  direct-nameserver-follow-policy: false
  nameserver-policy:
{{DNS_POLICIES}}

# ==================== 代理策略组 Proxy Groups ====================
proxy-groups:
{{PROXY_GROUPS}}

# ==================== 分流规则 Rules ====================
rules:
{{RULES}}

# ==================== 规则提供者 Rule Providers ====================
rule-providers:
{{RULE_PROVIDERS}}
