#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate AI profile outputs for OpenClash / Mihomo.

Outputs:
  - cfg/yaml/Custom_Clash_AI.yaml
  - cfg/yaml/Custom_Clash_AI_Strict.yaml
  - cfg/Custom_Clash_AI.ini
  - rule/AI_*_Classical.yaml

The generator keeps one source of truth for:
  - AI routing rulesets
  - strategy-group naming
  - repo links
  - zh-CN -> zh-HK wording used in user-facing group labels
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
RULE_DIR = ROOT / "rule"
CFG_DIR = ROOT / "cfg"
YAML_DIR = CFG_DIR / "yaml"

REPO_SLUG = "mythic3011/rules"
REPO_URL = f"https://github.com/{REPO_SLUG}"
BASE_URL = f"https://testingcf.jsdelivr.net/gh/{REPO_SLUG}@main"

ZH_HK_TERMS = {
    "手动选择": "手動選擇",
    "自动选择": "自動選擇",
    "全球直连": "全球直連",
    "美国节点": "美國節點",
    "日本节点": "日本節點",
    "新加坡节点": "新加坡節點",
    "台湾节点": "台灣節點",
    "韩国节点": "韓國節點",
    "漏网之鱼": "漏網之魚",
    "拒绝": "拒絕",
    "专用": "專用",
    "严格版": "嚴格版",
    "节点": "節點",
    "订阅": "訂閱",
    "转换": "轉換",
    "设置": "設定",
    "项目地址": "項目地址",
    "作者": "作者",
    "分组": "分組",
}


def zh_hk(text: str) -> str:
    for cn, hk in ZH_HK_TERMS.items():
        text = text.replace(cn, hk)
    return text


GROUP = {
    "manual": "🚀 手動選擇",
    "auto": "♻️ 自動選擇",
    "direct": "🎯 全球直連",
    "reject": "⛔ 拒絕",
    "fallback": "🐟 漏網之魚",
    "us": "🇺🇸 美國節點",
    "jp": "🇯🇵 日本節點",
    "sg": "🇸🇬 新加坡節點",
    "tw": "🇼🇸 台灣節點",
    "kr": "🇰🇷 韓國節點",
    "chatgpt": "🤖 ChatGPT",
    "copilot": "🤖 Copilot",
    "claude": "🤖 Claude",
    "gemini": "🤖 Gemini",
    "notebooklm": "🤖 NotebookLM",
    "perplexity": "🤖 Perplexity",
    "grok": "🤖 Grok",
    "poe": "🤖 Poe",
}

REGION_FILTERS = {
    "us": r"(?i)(🇺🇸|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|纽约|纽纽|亚特兰大|迈阿密|华盛顿|\bUS(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|United States|UnitedStates|UNITED STATES|USA|America|AMERICA|JFK|EWR|IAD|ATL|ORD|MIA|NYC|LAX|SFO|SEA|DFW|SJC)",
    "jp": r"(?i)(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|\bJP(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Japan|JAPAN|JPN|NRT|HND|KIX|TYO|OSA|关西|Kansai|KANSAI)",
    "sg": r"(?i)(🇸🇬|新加坡|坡|狮城|\bSG(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Singapore|SINGAPORE|SIN)",
    "tw": r"(?i)(🇹🇼|🇼🇸|台|新北|彰化|\bTW(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Taiwan|TAIWAN|TWN|TPE|ROC)",
    "kr": r"(?i)(🇰🇷|\bKR(?:[-_ ]?\d+(?:[-_ ]?[A-Za-z]{2,})?)?\b|Korea|KOREA|KOR|首尔|韩|韓|春川|Chuncheon|ICN)",
}

AI_RULESETS = [
    {
        "id": "AI_ChatGPT",
        "group": GROUP["chatgpt"],
        "file": "AI_ChatGPT_Classical.yaml",
        "payload": ["GEOSITE,openai"],
    },
    {
        "id": "AI_Copilot",
        "group": GROUP["copilot"],
        "file": "AI_Copilot_Classical.yaml",
        "payload": ["GEOSITE,bing", "DOMAIN-KEYWORD,copilot"],
    },
    {
        "id": "AI_Claude",
        "group": GROUP["claude"],
        "file": "AI_Claude_Classical.yaml",
        "payload": [
            "DOMAIN-SUFFIX,anthropic.com",
            "DOMAIN-SUFFIX,claude.ai",
            "DOMAIN-KEYWORD,anthropic",
            "DOMAIN-KEYWORD,claude",
        ],
    },
    {
        "id": "AI_Gemini",
        "group": GROUP["gemini"],
        "file": "AI_Gemini_Classical.yaml",
        "payload": [
            "DOMAIN-SUFFIX,ai.google.dev",
            "DOMAIN-SUFFIX,makersuite.google.com",
            "DOMAIN-SUFFIX,generativelanguage.googleapis.com",
        ],
    },
    {
        "id": "AI_NotebookLM",
        "group": GROUP["notebooklm"],
        "file": "AI_NotebookLM_Classical.yaml",
        "payload": [
            "DOMAIN-SUFFIX,notebooklm.google.com",
            "DOMAIN-SUFFIX,notebooklm.google",
        ],
    },
    {
        "id": "AI_Perplexity",
        "group": GROUP["perplexity"],
        "file": "AI_Perplexity_Classical.yaml",
        "payload": ["DOMAIN-SUFFIX,perplexity.ai", "DOMAIN-KEYWORD,perplexity"],
    },
    {
        "id": "AI_Grok",
        "group": GROUP["grok"],
        "file": "AI_Grok_Classical.yaml",
        "payload": ["DOMAIN-SUFFIX,x.ai", "DOMAIN-KEYWORD,xai", "DOMAIN-KEYWORD,grok"],
    },
    {
        "id": "AI_Poe",
        "group": GROUP["poe"],
        "file": "AI_Poe_Classical.yaml",
        "payload": ["DOMAIN-SUFFIX,poe.com", "DOMAIN-KEYWORD,poe"],
    },
]


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def indent(text: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(f"{prefix}{line}" if line else "" for line in text.splitlines())


def render_rule_file(item: dict[str, object]) -> str:
    lines = [
        "# Generated by py/generate_ai_profiles.py",
        f"# REPO: {REPO_URL}",
        f"# SOURCE: {REPO_URL}/blob/main/py/generate_ai_profiles.py",
        f"# GROUP: {item['group']}",
        f"# TOTAL: {len(item['payload'])}",
        "",
        "payload:",
    ]
    lines.extend(f"  - {rule}" for rule in item["payload"])
    return "\n".join(lines)


def render_proxy_groups(strict: bool) -> str:
    direct = GROUP["direct"]
    manual = GROUP["manual"]
    auto = GROUP["auto"]
    reject = GROUP["reject"]
    fallback = GROUP["fallback"]
    us = GROUP["us"]
    jp = GROUP["jp"]
    sg = GROUP["sg"]
    tw = GROUP["tw"]
    kr = GROUP["kr"]

    def group_block(name: str, group_type: str, lines: list[str]) -> str:
        block = [f'- name: "{name}"', f"  type: {group_type}"]
        block.extend(lines)
        return "\n".join(block)

    def ai_group(name: str, proxies: list[str]) -> str:
        lines = [
            '  url: "https://cp.cloudflare.com/generate_204"',
            "  interval: 300",
            "  proxies:",
        ]
        lines.extend(f'    - "{p}"' for p in proxies)
        return group_block(name, "fallback", lines)

    blocks = [
        group_block(
            manual,
            "select",
            [
                "  proxies:",
                f'    - "{auto}"',
                f'    - "{us}"',
                f'    - "{jp}"',
                f'    - "{sg}"',
                f'    - "{tw}"',
                f'    - "{kr}"',
                '  filter: "^(?!.*(DIRECT|直接连接|群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic|GB|Expire)).*$"',
                "  use:",
                "    - provider1",
            ],
        ),
        group_block(
            auto,
            "url-test",
            [
                '  filter: "^(?!.*(DIRECT|直接连接|群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|Traffic|GB|Expire)).*$"',
                "  tolerance: 50",
                '  url: "https://cp.cloudflare.com/generate_204"',
                "  interval: 300",
                "  use:",
                "    - provider1",
            ],
        ),
    ]

    service_proxies = {
        GROUP["chatgpt"]: [manual, auto, sg, us, jp, tw, kr, reject],
        GROUP["copilot"]: [manual, auto, direct, us, sg, jp, tw, kr, reject],
        GROUP["claude"]: [manual, auto, sg, us, jp, tw, kr, reject],
        GROUP["gemini"]: [manual, auto, direct, sg, us, jp, tw, kr, reject],
        GROUP["notebooklm"]: [manual, auto, direct, sg, us, jp, tw, kr, reject],
        GROUP["perplexity"]: [manual, auto, direct, sg, us, jp, tw, kr, reject],
        GROUP["grok"]: [manual, auto, direct, us, sg, jp, tw, kr, reject],
        GROUP["poe"]: [manual, auto, direct, sg, us, jp, tw, kr, reject],
    }

    for name, proxies in service_proxies.items():
        blocks.append(ai_group(name, proxies))

    blocks.append(group_block(reject, "select", ["  proxies:", "    - REJECT"]))
    fallback_proxies = [direct, manual]
    if not strict:
        fallback_proxies.append(auto)
    blocks.append(
        group_block(
            fallback,
            "select",
            ["  proxies:", *(f'    - "{proxy}"' for proxy in fallback_proxies)],
        )
    )

    for region in ("jp", "sg", "tw", "kr"):
        blocks.append(
            group_block(
                GROUP[region],
                "url-test",
                [
                    "  url: https://cp.cloudflare.com/generate_204",
                    f"  filter: '{REGION_FILTERS[region]}'",
                    "  use:",
                    "    - provider1",
                    "  interval: 300",
                    "  tolerance: 50",
                ],
            )
        )

    blocks.append(group_block(direct, "select", ["  proxies:", "    - DIRECT"]))
    return "\n".join(blocks).rstrip()


def render_rules() -> str:
    lines = [
        f'  - "GEOSITE,private,{GROUP["direct"]}"',
        f'  - "GEOIP,private,{GROUP["direct"]},no-resolve"',
        f'  - "RULE-SET,Custom_Direct_Domain,{GROUP["direct"]}"',
        f'  - "RULE-SET,Custom_Direct_IP,{GROUP["direct"]},no-resolve"',
        f'  - "RULE-SET,Custom_Proxy_Domain,{GROUP["manual"]}"',
        f'  - "RULE-SET,Custom_Proxy_IP,{GROUP["manual"]},no-resolve"',
    ]
    lines.extend(f'  - "RULE-SET,{item["id"]},{item["group"]}"' for item in AI_RULESETS)
    lines.extend(
        [
            f'  - "GEOIP,HK,{GROUP["direct"]},no-resolve"',
            f'  - "MATCH,{GROUP["fallback"]}"',
        ]
    )
    return "\n".join(lines)


def render_rule_providers() -> str:
    providers = [
        (
            "Custom_Direct_Domain",
            "domain",
            f"{BASE_URL}/rule/Custom_Direct_Domain.mrs",
            "mrs",
        ),
        (
            "Custom_Direct_IP",
            "ipcidr",
            f"{BASE_URL}/rule/Custom_Direct_IP.mrs",
            "mrs",
        ),
        (
            "Custom_Proxy_Domain",
            "domain",
            f"{BASE_URL}/rule/Custom_Proxy_Domain.mrs",
            "mrs",
        ),
        (
            "Custom_Proxy_IP",
            "ipcidr",
            f"{BASE_URL}/rule/Custom_Proxy_IP.mrs",
            "mrs",
        ),
    ]
    for item in AI_RULESETS:
        providers.append((item["id"], "classical", f"{BASE_URL}/rule/{item['file']}", "yaml"))

    blocks = []
    for name, behavior, url, fmt in providers:
        blocks.append(
            "\n".join(
                [
                    f"{name}:",
                    f"  behavior: {behavior}",
                    "  interval: 10800",
                    "  type: http",
                    f'  url: "{url}"',
                    f"  format: {fmt}",
                ]
            )
        )
    return "\n\n".join(blocks)


def render_yaml(strict: bool) -> str:
    title = zh_hk("YAML 配置文件（AI 专用严格版）" if strict else "YAML 配置文件（AI 专用）")
    lines = [
        "# Custom_OpenClash_Rules",
        f"# {title}",
        "# 適用於需要 AI 分流與 DNS 洩漏保護的 OpenWrt / OpenClash 場景",
        "# 基於 Custom_Clash.yaml 精簡：僅保留 AI 分流與基礎網路配置",
    ]
    if strict:
        lines.append(
            "# 嚴格版說明：預設僅走代理；按需求僅對指定 Provider 開放直連"
            "（如 Copilot/Perplexity/Gemini/NotebookLM/Grok/Poe）"
        )
    lines.extend(
        [
            "# GENERATED by py/generate_ai_profiles.py. Do not edit manually.",
            "",
            "# ==================== 端口配置 Port Configuration ====================",
            "port: 7890",
            "socks-port: 7891",
            "mixed-port: 7893",
            "redir-port: 7892",
            "tproxy-port: 7895",
            "allow-lan: true",
            'bind-address: "*"',
            "mode: rule",
            "tcp-concurrent: true",
            "unified-delay: true",
            "",
            "# ==================== 代理提供者 Proxy Provider ====================",
            "proxy-providers:",
            "  provider1:",
            "    type: http",
            '    url: "url"',
            "    interval: 3600",
            "    path: ./proxy_provider/provider1.yaml",
            "    proxy: DIRECT",
            "    header:",
            "    health-check:",
            "      enable: true",
            "      interval: 600",
            "      url: https://cp.cloudflare.com/generate_204",
            "    override:",
            "      skip-cert-verify: true",
            "      udp: true",
            "",
            "# ==================== 地理数据库配置 GeoData Configuration ====================",
            "geox-url:",
            "  mmdb: https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/Country.mmdb",
            "  geoip: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat",
            "  geosite: https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat",
            "  asn: https://testingcf.jsdelivr.net/gh/xishang0128/geoip@release/GeoLite2-ASN.mmdb",
            "geo-auto-update: true",
            "geo-update-interval: 24",
            "geodata-mode: true",
            "",
            "# ==================== 日志与控制 ====================",
            "log-level: info",
            "ipv6: true",
            "external-controller: 0.0.0.0:9090",
            "",
            "# ==================== 配置文件存储 Profile ====================",
            "profile:",
            "  store-selected: true",
            "  store-fake-ip: true",
            "",
            "# ==================== TUN 虚拟网卡配置 ====================",
            "tun:",
            "  enable: true",
            "  stack: system",
            "  dns-hijack:",
            "    - 0.0.0.0:53",
            "  auto-detect-interface: false",
            "  auto-route: false",
            "  auto-redirect: false",
            "  strict-route: false",
            "  endpoint-independent-nat: true",
            "",
            "# ==================== DNS 配置 ====================",
            "dns:",
            "  enable: true",
            "  listen: 0.0.0.0:7874",
            "  ipv6: true",
            "  enhanced-mode: fake-ip",
            "  fake-ip-range: 198.18.0.1/16",
            "  fake-ip-filter:",
            '    - "*.lan"',
            "    - localhost.ptlogin2.qq.com",
            "  fake-ip-filter-mode: blacklist",
            "  respect-rules: true",
            "  default-nameserver:",
            "    - 1.1.1.1",
            "    - 8.8.8.8",
            "  nameserver:",
            "    - https://1.1.1.1/dns-query",
            "    - https://dns.google/dns-query",
            "    - https://dns.adguard-dns.com/dns-query",
            "  proxy-server-nameserver:",
            "    - https://1.1.1.1/dns-query",
            "    - https://dns.google/dns-query",
            "    - https://dns.adguard-dns.com/dns-query",
            "  direct-nameserver:",
            "    - https://127.0.0.1:5053/dns-query",
            "  direct-nameserver-follow-policy: false",
            "  nameserver-policy:",
            '    "geosite:private":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "geosite:cn":',
            "      - https://127.0.0.1:5053/dns-query",
            '    "geosite:openai":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "geosite:bing":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "geosite:category-ads-all":',
            "      - https://dns.adguard-dns.com/dns-query",
            "      - https://1.1.1.1/dns-query",
            '    "+.anthropic.com":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "+.claude.ai":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "+.perplexity.ai":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "+.x.ai":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            '    "+.poe.com":',
            "      - https://1.1.1.1/dns-query",
            "      - https://dns.google/dns-query",
            "",
            "# ==================== 代理策略组 Proxy Groups ====================",
            "proxy-groups:",
            indent(render_proxy_groups(strict), 2),
            "",
            "# ==================== 分流规则 Rules ====================",
            "rules:",
            indent(render_rules(), 2),
            "",
            "# ==================== 规则提供者 Rule Providers ====================",
            "rule-providers:",
            indent(render_rule_providers(), 2),
        ]
    )
    return "\n".join(lines)


def render_ini() -> str:
    direct = GROUP["direct"]
    manual = GROUP["manual"]
    auto = GROUP["auto"]
    reject = GROUP["reject"]
    fallback = GROUP["fallback"]
    us = GROUP["us"]
    jp = GROUP["jp"]
    sg = GROUP["sg"]
    tw = GROUP["tw"]
    kr = GROUP["kr"]

    rule_lines = [
        ";Custom_OpenClash_Rules",
        f";{zh_hk('AI 专用订阅转换模板（多 Provider 分组）')}",
        f";{zh_hk('作者')}：{REPO_URL}",
        f";{zh_hk('项目地址')}：{REPO_URL}",
        ";基於 Custom_Clash.ini 精簡並拆分 AI 服務策略組",
        ";GENERATED by py/generate_ai_profiles.py. Do not edit manually.",
        "",
        "[custom]",
        ";設定規則標誌位",
        ";以下規則按由上而下順序遍歷，優先命中上位規則，規則重複無影響",
        "",
        f"ruleset={direct},[]GEOSITE,private",
        f"ruleset={direct},[]GEOIP,private,no-resolve",
        f"ruleset={direct},clash-domain:{BASE_URL}/rule/Custom_Direct_Domain.yaml,28800",
        f"ruleset={direct},clash-classic:{BASE_URL}/rule/Custom_Direct_Classical_IP.yaml,28800",
        f"ruleset={manual},clash-domain:{BASE_URL}/rule/Custom_Proxy_Domain.yaml,28800",
        f"ruleset={manual},clash-classic:{BASE_URL}/rule/Custom_Proxy_Classical_IP.yaml,28800",
    ]
    for item in AI_RULESETS:
        rule_lines.append(
            f'ruleset={item["group"]},clash-classic:{BASE_URL}/rule/{item["file"]},28800'
        )
    rule_lines.extend(
        [
            f"ruleset={direct},[]GEOIP,HK,no-resolve",
            f"ruleset={fallback},[]FINAL",
            ";設定節點分組標誌位",
            f"custom_proxy_group={manual}`select`[]{auto}`[]{us}`[]{jp}`[]{sg}`[]{tw}`[]{kr}`.*",
            f"custom_proxy_group={auto}`fallback`[]{us}`[]{sg}`[]{jp}`[]{tw}`[]{kr}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['chatgpt']}`fallback`[]{manual}`[]{auto}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['copilot']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{us}`[]{sg}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['claude']}`fallback`[]{manual}`[]{auto}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['gemini']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['notebooklm']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['perplexity']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['grok']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{us}`[]{sg}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={GROUP['poe']}`fallback`[]{manual}`[]{auto}`[]{direct}`[]{sg}`[]{us}`[]{jp}`[]{tw}`[]{kr}`[]{reject}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={reject}`select`[]REJECT",
            f"custom_proxy_group={fallback}`select`[]{direct}`[]{manual}`[]{auto}",
            f"custom_proxy_group={us}`url-test`{REGION_FILTERS['us']}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={jp}`url-test`{REGION_FILTERS['jp']}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={sg}`url-test`{REGION_FILTERS['sg']}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={tw}`url-test`{REGION_FILTERS['tw']}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={kr}`url-test`{REGION_FILTERS['kr']}`https://cp.cloudflare.com/generate_204`300,,50",
            f"custom_proxy_group={direct}`select`[]DIRECT",
            ";下方參數請勿修改",
            "enable_rule_generator=true",
            "overwrite_original_rules=true",
        ]
    )
    return "\n".join(rule_lines) + "\n"


def main() -> None:
    for item in AI_RULESETS:
        write_text(RULE_DIR / item["file"], render_rule_file(item))

    write_text(YAML_DIR / "Custom_Clash_AI.yaml", render_yaml(strict=False))
    write_text(YAML_DIR / "Custom_Clash_AI_Strict.yaml", render_yaml(strict=True))
    write_text(CFG_DIR / "Custom_Clash_AI.ini", render_ini())
    print("Generated AI profile outputs.")


if __name__ == "__main__":
    main()
