from __future__ import annotations

"""Legacy compatibility exports backed by the declarative AI catalog.

New implementation code should consume ``load_catalog()`` and typed models instead
of importing these dictionaries. They remain here so existing tests/tools that
import ``internal/python/generate_ai_profiles.py`` do not break during the staged refactor.
"""

from .catalog import load_catalog
from .settings import REPO_URL
from .static_rules import (
    BUILTIN_DIRECT,
    BUILTIN_REJECT,
    MANAGED_TAILSCALE_DOMAIN_MARKER,
    MANAGED_TAILSCALE_IP_MARKER,
    TAILSCALE_DOMAIN_ENTRIES,
    ZH_HK_TERMS,
)

_CATALOG = load_catalog()

PROVIDER_NOISE_EXCLUDE_TERMS = _CATALOG.provider_noise_exclude_terms
PROVIDER_NOISE_EXCLUDE_PATTERN = _CATALOG.provider_noise_exclude_pattern
AI_HK_EXCLUDE_TERMS = _CATALOG.ai_hk_exclude_terms
AI_HK_EXCLUDE_PATTERN = rf"(?i)({AI_HK_EXCLUDE_TERMS})"
AI_POOL_FILTER = _CATALOG.ai_pool_filter

GROUP = dict(_CATALOG.groups)
PRIMARY_REGION_ORDER = tuple(region.id for region in _CATALOG.primary_regions)
ALL_REGION_ORDER = (*PRIMARY_REGION_ORDER, "other")
REGION_TERMS = {region.id: region.terms for region in _CATALOG.primary_regions}
REGION_FILTERS = {region.id: region.filter_pattern for region in _CATALOG.primary_regions}
KNOWN_REGION_TERMS = "|".join(rf"(?:{REGION_TERMS[region]})" for region in PRIMARY_REGION_ORDER)
KNOWN_REGION_EXCLUDE_PATTERN = _CATALOG.known_region_exclude_pattern
OTHER_REGION_FILTER = _CATALOG.other_region_filter

AI_SERVICES = [
    {
        "id": service.id,
        "provider_key": service.provider_key,
        "group": service.group,
        "file": service.file,
        "geosites": service.geosites,
        "payload": list(service.payload),
        "regions": service.regions,
        "direct_relaxed": service.direct_relaxed,
    }
    for service in _CATALOG.services
    if "subconverter" in service.projections
]
AI_RULESETS = [
    {
        "provider_key": service.provider_key,
        "group": service.group,
        "file": service.file,
        "payload": list(service.payload),
    }
    for service in _CATALOG.services
    if service.payload
]
AI_GUARD_GEOSITES = _CATALOG.ai_guard_geosites
MANAGED_AI_RULE_FILES = set(_CATALOG.managed_ai_rule_files)

def _legacy_comment_lines(item):
    return [
        "# Generated by internal/python/generate_ai_profiles.py",
        f"# REPO: {REPO_URL}",
        f"# SOURCE: {REPO_URL}/blob/main/internal/python/generate_ai_profiles.py",
        *item.comment_lines,
    ]


SSH_RULESETS = [
    {
        "provider_key": item.provider_key,
        "group": item.group,
        "file": item.file,
        "payload": list(item.payload),
        "comment_lines": _legacy_comment_lines(item),
    }
    for item in _CATALOG.companion_rulesets
    if item.category == "ssh"
]

_gaming = next(item for item in _CATALOG.companion_rulesets if item.category == "gaming")
GAMING_RULESET = {
    "provider_key": _gaming.provider_key,
    "group": _gaming.group,
    "file": _gaming.file,
    "payload": list(_gaming.payload),
    "comments": list(_gaming.comments),
}

PROCESS_RULESET_SPECS = [
    {
        "key": item.key,
        "provider_key": item.provider_key,
        "file": item.file,
        "group": item.group,
    }
    for item in _CATALOG.process_rulesets
]
PROCESS_RULES_WARNING = list(_CATALOG.process_rules_warning)
