#!/usr/bin/env python3
"""Generate the GitHub Service Intake Issue Form from the Region Registry."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REGIONS = ROOT / "internal/config/ai-routing/catalogs/regions.json"
OUTPUT = ROOT / ".github/ISSUE_TEMPLATE/service_intake.yml"
MAX_ADDITIONAL_REGIONS = 3


def q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> None:
    doc = json.loads(REGIONS.read_text(encoding="utf-8"))
    options = [f"{r['id']} — {r.get('name', r['id'])}" for r in doc["regions"]]
    lines = [
        "# GENERATED by internal/python/generate_service_intake_form.py. Do not edit by hand.",
        'name: "🌍 Regional service intake"',
        "description: Report service matchers and observed regional availability; automation proposes the registry change.",
        'title: "[Service Intake]: "',
        'labels: ["service-intake"]',
        "body:",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        Submit observed facts. You do not need to know the routing implementation.",
        "        Generated cfg/rule files are never edited from this form.",
        "        If a region is missing, use the Additional / unlisted regions section below.",
        "  - type: input", "    id: service_name", "    attributes:", "      label: Service name", "      placeholder: Example AI", "    validations: {required: true}",
        "  - type: input", "    id: service_id", "    attributes:", "      label: Service ID (optional)", "      description: Lowercase slug. Leave blank to derive it from the service name.",
        "  - type: dropdown", "    id: matcher_type", "    attributes:", "      label: Matcher type", "      options:",
    ]
    lines += [f"        - {q(x)}" for x in ["DOMAIN-SUFFIX", "DOMAIN", "DOMAIN-KEYWORD", "IP-CIDR", "PROCESS-NAME", "PROCESS-PATH"]]
    lines += [
        "    validations: {required: true}",
        "  - type: textarea", "    id: matcher_values", "    attributes:", "      label: Matcher values", "      description: One value per line. Do not include matcher prefixes.", "      placeholder: |", "        example.com", "        api.example.com", "    validations: {required: true}",
        "  - type: dropdown", "    id: working_regions", "    attributes:", "      label: Confirmed working regions", "      multiple: true", "      options:",
    ]
    lines += [f"        - {q(x)}" for x in options]
    lines += [
        "    validations: {required: true}",
        "  - type: dropdown", "    id: blocked_regions", "    attributes:", "      label: Confirmed blocked regions", "      multiple: true", "      options:",
    ]
    lines += [f"        - {q(x)}" for x in options]
    lines += [
        "  - type: checkboxes",
        "    id: add_unlisted_regions",
        "    attributes:",
        "      label: Other / new region",
        "      description: Tick this if one or more relevant regions are not listed above, then fill the slots below.",
        "      options:",
        "        - label: I need to add one or more unlisted regions.",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        ### Additional / unlisted regions",
        "        You can add up to three regions in the same ticket. The canonical region ID, flag, group name and regex are generated automatically.",
        "        Use the code field for short codes such as `IS`; do not repeat two-letter codes as loose node keywords.",
    ]
    for slot in range(1, MAX_ADDITIONAL_REGIONS + 1):
        prefix = f"Additional region {slot}"
        lines += [
            "  - type: dropdown", f"    id: additional_region_{slot}_status", "    attributes:", f"      label: {prefix} status", "      options: [\"Not used\", \"Works\", \"Blocked\"]",
            "  - type: input", f"    id: additional_region_{slot}_code", "    attributes:", f"      label: {prefix} code", "      description: 2-3 letter country/region code. The canonical ID is derived from this value.", "      placeholder: IS",
            "  - type: input", f"    id: additional_region_{slot}_name", "    attributes:", f"      label: {prefix} name", "      placeholder: Iceland",
            "  - type: textarea", f"    id: additional_region_{slot}_aliases", "    attributes:", f"      label: {prefix} aliases", "      description: Optional human names, one per line. The primary name is added automatically.", "      placeholder: |", "        Ísland",
            "  - type: textarea", f"    id: additional_region_{slot}_keywords", "    attributes:", f"      label: {prefix} node keywords", "      description: Optional provider-node city/airport/emoji terms, one per line.", "      placeholder: |", "        Reykjavik", "        KEF", "        🇮🇸",
            "  - type: dropdown", f"    id: additional_region_{slot}_routable", "    attributes:", f"      label: {prefix} routing exit", "      description: Yes means provider nodes from this newly created region may be selected as exits.", "      options: [\"No — observation only\", \"Yes — add as routing exit\"]",
        ]
    lines += [
        "  - type: checkboxes", "    id: confirmation", "    attributes:", "      label: Confirmation", "      options:", "        - label: I am reporting observed service reachability, not requesting arbitrary code execution.", "          required: true",
    ]
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
