#!/bin/sh
# Fail closed for selected AI providers by blocking direct LAN forwarding.

set -eu

ENABLE_AI_FAILCLOSED="${ENABLE_AI_FAILCLOSED:-1}"
ENABLE_AI_FAILCLOSED_CHATGPT="${ENABLE_AI_FAILCLOSED_CHATGPT:-0}"
ENABLE_AI_FAILCLOSED_COPILOT="${ENABLE_AI_FAILCLOSED_COPILOT:-0}"
ENABLE_AI_FAILCLOSED_CLAUDE="${ENABLE_AI_FAILCLOSED_CLAUDE:-1}"
ENABLE_AI_FAILCLOSED_GEMINI="${ENABLE_AI_FAILCLOSED_GEMINI:-0}"
ENABLE_AI_FAILCLOSED_NOTEBOOKLM="${ENABLE_AI_FAILCLOSED_NOTEBOOKLM:-0}"
ENABLE_AI_FAILCLOSED_PERPLEXITY="${ENABLE_AI_FAILCLOSED_PERPLEXITY:-0}"
ENABLE_AI_FAILCLOSED_GROK="${ENABLE_AI_FAILCLOSED_GROK:-0}"
ENABLE_AI_FAILCLOSED_POE="${ENABLE_AI_FAILCLOSED_POE:-0}"
ENABLE_AI_FAILCLOSED_IPV6="${ENABLE_AI_FAILCLOSED_IPV6:-0}"
DNSMASQ_RESTART="${DNSMASQ_RESTART:-1}"
NFT_TABLE_FAMILY="${NFT_TABLE_FAMILY:-inet}"
NFT_TABLE_NAME="${NFT_TABLE_NAME:-fw4}"
NFT_FORWARD_CHAIN="${NFT_FORWARD_CHAIN:-forward}"
NFT_CHAIN_NAME="${NFT_CHAIN_NAME:-rules_ai_failclosed}"
NFT_SET_PREFIX="${NFT_SET_PREFIX:-rules_ai}"
DNSMASQ_CONF_NAME="${DNSMASQ_CONF_NAME:-rules-ai-failclosed.conf}"

log() {
    echo "[rules-ai-failclosed] $*"
}

env_flag() {
    var_name="$1"
    eval "raw_value=\${$var_name:-0}"
    case "$raw_value" in
        1|true|TRUE|yes|YES|on|ON) echo "1" ;;
        *) echo "0" ;;
    esac
}

detect_dnsmasq_dir() {
    uci_output="$(uci show dhcp.@dnsmasq[0] 2>/dev/null || true)"

    if echo "$uci_output" | grep -qE 'cfg[0-9a-f]{6}'; then
        hash_id="$(echo "$uci_output" | grep -oE 'cfg[0-9a-f]{6}' | head -1)"
        echo "/tmp/dnsmasq.${hash_id}.d"
        return 0
    fi

    if echo "$uci_output" | grep -qE '@dnsmasq\[[0-9]+\]'; then
        echo "/tmp/dnsmasq.d"
        return 0
    fi

    fallback_dir="$(find /tmp -maxdepth 1 -type d -name 'dnsmasq.*.d' | head -n 1)"
    if [ -n "$fallback_dir" ]; then
        echo "$fallback_dir"
        return 0
    fi

    return 1
}

provider_domains() {
    provider="$1"
    case "$provider" in
        chatgpt)
            printf '%s\n' \
                chatgpt.com \
                openai.com \
                oaistatic.com \
                oaiusercontent.com \
                chat.openai.com \
                ios.chat.openai.com
            ;;
        copilot)
            printf '%s\n' \
                bing.com \
                copilot.microsoft.com \
                copilot.cloud.microsoft
            ;;
        claude)
            printf '%s\n' \
                anthropic.com \
                claude.ai
            ;;
        gemini)
            printf '%s\n' \
                ai.google.dev \
                bard.google.com \
                gemini.google.com \
                generativelanguage.googleapis.com \
                makersuite.google.com
            ;;
        notebooklm)
            printf '%s\n' \
                notebooklm.google \
                notebooklm.google.com
            ;;
        perplexity)
            printf '%s\n' \
                perplexity.ai
            ;;
        grok)
            printf '%s\n' \
                grok.com \
                x.ai
            ;;
        poe)
            printf '%s\n' \
                poe.com
            ;;
    esac
}

provider_enabled_var() {
    provider="$1"
    case "$provider" in
        chatgpt) echo "ENABLE_AI_FAILCLOSED_CHATGPT" ;;
        copilot) echo "ENABLE_AI_FAILCLOSED_COPILOT" ;;
        claude) echo "ENABLE_AI_FAILCLOSED_CLAUDE" ;;
        gemini) echo "ENABLE_AI_FAILCLOSED_GEMINI" ;;
        notebooklm) echo "ENABLE_AI_FAILCLOSED_NOTEBOOKLM" ;;
        perplexity) echo "ENABLE_AI_FAILCLOSED_PERPLEXITY" ;;
        grok) echo "ENABLE_AI_FAILCLOSED_GROK" ;;
        poe) echo "ENABLE_AI_FAILCLOSED_POE" ;;
    esac
}

write_dnsmasq_conf() {
    conf_file="$1"
    : > "$conf_file"
    {
        echo "# Generated by setup/openclash/scripts/apply_ai_failclosed.sh"
        echo "# Uses dnsmasq nftset population; does not write /etc/hosts."
    } >> "$conf_file"

    for provider in chatgpt copilot claude gemini notebooklm perplexity grok poe; do
        enabled_var="$(provider_enabled_var "$provider")"
        [ "$(env_flag "$enabled_var")" = "1" ] || continue
        set_v4="${NFT_SET_PREFIX}_${provider}_v4"
        set_v6="${NFT_SET_PREFIX}_${provider}_v6"
        provider_domains "$provider" | while IFS= read -r domain; do
            [ -n "$domain" ] || continue
            if [ "$ENABLE_AI_FAILCLOSED_IPV6" = "1" ]; then
                echo "nftset=/${domain}/4#${NFT_TABLE_FAMILY}#${NFT_TABLE_NAME}#${set_v4},6#${NFT_TABLE_FAMILY}#${NFT_TABLE_NAME}#${set_v6}" >> "$conf_file"
            else
                echo "nftset=/${domain}/4#${NFT_TABLE_FAMILY}#${NFT_TABLE_NAME}#${set_v4}" >> "$conf_file"
            fi
        done
    done
}

delete_rule_by_comment() {
    chain="$1"
    comment="$2"
    nft -a list chain "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$chain" 2>/dev/null \
        | awk -v comment="$comment" '$0 ~ comment { print $NF }' \
        | while IFS= read -r handle; do
            [ -n "$handle" ] || continue
            nft delete rule "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$chain" handle "$handle" 2>/dev/null || true
        done
}

reset_nft_objects() {
    delete_rule_by_comment "$NFT_FORWARD_CHAIN" "rules-ai-failclosed-jump"
    nft delete chain "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$NFT_CHAIN_NAME" 2>/dev/null || true

    for provider in chatgpt copilot claude gemini notebooklm perplexity grok poe; do
        nft delete set "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "${NFT_SET_PREFIX}_${provider}_v4" 2>/dev/null || true
        nft delete set "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "${NFT_SET_PREFIX}_${provider}_v6" 2>/dev/null || true
    done
}

create_nft_objects() {
    nft add chain "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$NFT_CHAIN_NAME"
    nft insert rule "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$NFT_FORWARD_CHAIN" jump "$NFT_CHAIN_NAME" comment "rules-ai-failclosed-jump"

    for provider in chatgpt copilot claude gemini notebooklm perplexity grok poe; do
        enabled_var="$(provider_enabled_var "$provider")"
        [ "$(env_flag "$enabled_var")" = "1" ] || continue
        nft add set "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "${NFT_SET_PREFIX}_${provider}_v4" "{ type ipv4_addr; flags interval; }"
        if [ "$ENABLE_AI_FAILCLOSED_IPV6" = "1" ]; then
            nft add set "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "${NFT_SET_PREFIX}_${provider}_v6" "{ type ipv6_addr; flags interval; }"
        fi
    done
}

openclash_running() {
    /etc/init.d/openclash status 2>/dev/null | grep -q running
}

apply_block_rules() {
    if openclash_running; then
        log "OpenClash is running; direct LAN forwarding to enabled AI providers remains blocked"
    else
        log "OpenClash is not running; enabled AI providers are fail-closed"
    fi

    for provider in chatgpt copilot claude gemini notebooklm perplexity grok poe; do
        enabled_var="$(provider_enabled_var "$provider")"
        [ "$(env_flag "$enabled_var")" = "1" ] || continue
        nft add rule "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$NFT_CHAIN_NAME" ip daddr "@${NFT_SET_PREFIX}_${provider}_v4" reject comment "rules-ai-failclosed-${provider}-v4"
        if [ "$ENABLE_AI_FAILCLOSED_IPV6" = "1" ]; then
            nft add rule "$NFT_TABLE_FAMILY" "$NFT_TABLE_NAME" "$NFT_CHAIN_NAME" ip6 daddr "@${NFT_SET_PREFIX}_${provider}_v6" reject comment "rules-ai-failclosed-${provider}-v6"
        fi
    done
}

main() {
    if [ "$ENABLE_AI_FAILCLOSED" != "1" ]; then
        log "disabled; removing nft objects"
        reset_nft_objects
        exit 0
    fi

    if ! command -v nft >/dev/null 2>&1; then
        log "nft is required on fw4 OpenWrt"
        exit 1
    fi

    dnsmasq_dir="$(detect_dnsmasq_dir)" || {
        log "unable to detect dnsmasq rule directory"
        exit 1
    }
    mkdir -p "$dnsmasq_dir"

    reset_nft_objects
    create_nft_objects
    write_dnsmasq_conf "${dnsmasq_dir}/${DNSMASQ_CONF_NAME}"

    if [ "$DNSMASQ_RESTART" = "1" ]; then
        /etc/init.d/dnsmasq restart
    fi

    apply_block_rules
    log "done"
}

main "$@"
